spring:
  jpa:
    properties:
      hibernate:
        format_sql: false
app:
  notification:
    email:
      from: "me@mohsen.work"
      unsubscribe-url: "https://teampilot.app/unsubscribe"
      company-name: "Teampilot"
      base-url: "https://my.teampilot.app"
